=== hectormendozam/tecweb/ejemplos/XML/XML02 - ejemplo_DTD/LISTA.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT lista (persona)+>
<!ELEMENT persona (nombre, email*, relacion?)>
<!ATTLIST persona id ID #REQUIRED>
<!ATTLIST persona sexo (hombre | mujer) #IMPLIED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT relacion EMPTY>
<!ATTLIST relacion amigo-de IDREFS #IMPLIED
enemigo-de IDREFS #IMPLIED>

=== hectormendozam/tecweb/ejemplos/XML/XML02 - ejemplo_DTD/lista.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE lista SYSTEM "LISTA.dtd">
<lista>
    <persona sexo="hombre" id="Beatriz">
        <nombre>Beatriz Barrientos</nombre>
        <email>betyb@gmail.com</email>
        <email>betyb@yahoo.com</email>
    </persona>
    <persona sexo="hombre" id="Alvaro">
        <nombre>Álvaro Álvarado</nombre>
        <email>alvaroal@gmail.com</email>
        <relacion amigo-de="Beatriz"/>
    </persona>
</lista>
